---
- name: Create Ollama docker directory
  ansible.builtin.file:
    path: "{{ ollama_docker_path }}"
    owner: "{{ ollama_docker_owner }}"
    group: "{{ ollama_docker_group }}"
    state: directory
    mode: "0750"

- name: Manage Ollama docker compose configuration
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ ollama_docker_path }}/compose.yaml"
    owner: "{{ ollama_docker_owner }}"
    group: "{{ ollama_docker_group }}"
    mode: "0640"
  notify: restart ollama

- name: Manage Ollama docker compose override configuration
  ansible.builtin.template:
    src: compose.override.yaml.j2
    dest: "{{ ollama_docker_path }}/compose.override.yaml"
    owner: "{{ ollama_docker_owner }}"
    group: "{{ ollama_docker_group }}"
    mode: "0640"
  when:
    - ollama_docker_compose_override is defined
    - ollama_docker_compose_override | length > 0
  notify: restart ollama

- name: Validate Ollama docker compose configuration
  ansible.builtin.command:
    cmd: docker compose config --quiet
    chdir: "{{ ollama_docker_path }}"
  changed_when: false

- name: Start Ollama docker compose deployment
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain up --detach
    chdir: "{{ ollama_docker_path }}"
  register: ollama_
  changed_when: "'Started' in ollama_.stdout"
