---
- name: Create Open WebUI docker directory
  ansible.builtin.file:
    path: "{{ openwebui_docker_path }}"
    owner: "{{ openwebui_docker_owner }}"
    group: "{{ openwebui_docker_group }}"
    state: directory
    mode: "0750"

- name: Manage Open WebUI docker compose configuration
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ openwebui_docker_path }}/compose.yaml"
    owner: "{{ openwebui_docker_owner }}"
    group: "{{ openwebui_docker_group }}"
    mode: "0640"
  notify: restart openwebui

- name: Manage Open WebUI docker compose override configuration
  ansible.builtin.template:
    src: compose.override.yaml.j2
    dest: "{{ openwebui_docker_path }}/compose.override.yaml"
    owner: "{{ openwebui_docker_owner }}"
    group: "{{ openwebui_docker_group }}"
    mode: "0640"
  when:
    - openwebui_docker_compose_override is defined
    - openwebui_docker_compose_override | length > 0
  notify: restart openwebui

- name: Validate Open WebUI docker compose deployment
  ansible.builtin.command:
    cmd: docker compose config --quiet
    chdir: "{{ openwebui_docker_path }}"
  changed_when: false

- name: Start Open WebUI docker compose deployment
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain up --detach
    chdir: "{{ openwebui_docker_path }}"
  register: openwebui_
  changed_when: "'Started' in openwebui_.stdout"
